name: NPM Build Deploy
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  npm-build:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Started NPM Build Job"
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Checking NodeJs & NPM Versions
        run: |
          echo "Node Version check"
          node -v
          echo "NPM Version check"
          npm -v
      - name: Install dependencies
        run: |
          npm install
          npm ci
      - name: Build for prod
        run: |
          npm run build
      - name: Set up Git for deployment
        run: |
            git config user.name "GitHub Actions"
            git config user.email "actions@github.com"
      - name: Deploy to Github Pages
        run: npm run deploy